---
title: "imdb_plot"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, message = F, include = F}
library(tidyverse)
library(plotly)

knitr::opts_chunk$set(
  message = F,
  warning = F
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r, include = F}
imdb_raw = 
  read_csv("./data/movie_metadata.csv") %>% 
  as.data.frame() %>% 
  drop_na(movie_title)
```


```{r, include = F}
imdb = 
  imdb_raw %>%
  as.data.frame() %>% 
  select(
    -color, -actor_2_name, -actor_2_facebook_likes, -actor_3_name, -actor_3_facebook_likes, -facenumber_in_poster, -movie_imdb_link, -content_rating, -plot_keywords
  ) %>%
  drop_na(gross)

rownames(imdb) = c(1:dim(imdb)[1])
```

```{r, include = F}
genres_list = unique(unlist(str_split(imdb$genres, "[|]")))
niubility = as.data.frame(matrix(0, nrow=dim(imdb)[1], ncol=length(genres_list)))
colnames(niubility) = genres_list
for (i in 1:dim(imdb)[1]){
  b = unlist(str_split(imdb$genres[i], "[|]"))
  for (word in b){
    niubility[i, word] = 1
    }
  }
rownames(niubility) = c(1:dim(imdb)[1])
imdb_after_genre = data.frame(imdb, niubility)
```

### Circular barplot

```{r, include = F}
circular_plot_df = 
  imdb_after_genre %>% 
  select(movie_title, gross, genres) %>% 
  arrange(desc(gross)) %>% 
  mutate(id = 1:dim(imdb_after_genre)[1]) %>% 
  filter(id < 20) %>%
  drop_na(movie_title, gross) %>% 
  mutate(movie_title = str_replace(movie_title,"\\?$","")) %>% 
  separate(genres,
           sep = "\\|",
           into = c("g1","g2","g3","g4","g5","g6","g7","g8")) %>% 
  pivot_longer(g1:g8,
               names_to = "dummy",
               values_to = "genres") %>%
  select(-dummy) %>% 
  drop_na(genres)
```


```{r, include = F}
data = 
  circular_plot_df %>% 
  mutate(genres = as.factor(genres)) %>% 
  select(movie_title, gross, genres)

head(data)
```

```{r, include = F}
empty_bar = 4
to_add = data.frame(matrix(NA, empty_bar*nlevels(data$genres), ncol(data)))
colnames(to_add) = colnames(data)
to_add$genres = rep(levels(data$genres), each=empty_bar)
data = rbind(data, to_add)
data = data %>% arrange(genres)
data$id = seq(1, nrow(data))
```


```{r, include = F}
# Get the name and the y position of each label
label_data = data
number_of_bar = nrow(label_data)
angle = 90 - 360 * (label_data$id-0.5) /number_of_bar   
label_data$hjust = ifelse( angle < -90, 1, 0)
label_data$angle = ifelse(angle < -90, angle+180, angle)
head(label_data)
```


```{r, include = F}
# prepare a data frame for base lines
base_data =
  data %>% 
  group_by(genres) %>% 
  summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))
head(base_data)

# prepare a data frame for grid (scales)
grid_data <- base_data
grid_data$end <- grid_data$end[ c(nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]
grid_data
```


```{r, message=FALSE, warning=FALSE}
bar_plot = 
  ggplot(data, aes(x=as.factor(id), y=gross, fill=genres)) +   
  geom_bar(aes(x=as.factor(id), y=gross, fill=genres), stat="identity", alpha=0.5) +
    geom_segment(data=grid_data, aes(x = end, y = 80, xend = start, yend = 80), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = end, y = 60, xend = start, yend = 60), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = end, y = 40, xend = start, yend = 40), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) +
    geom_segment(data=grid_data, aes(x = end, y = 20, xend = start, yend = 20), colour = "grey", alpha=1, size=0.3 , inherit.aes = FALSE ) 

anno_plot = 
  bar_plot +
    annotate("text", x = rep(max(data$id),4), y = c(20, 40, 60, 80), label = c("20", "40", "60", "80") , color="grey", size=3 , angle=0, fontface="bold", hjust=1) +
    ylim(-500000000, max(data$gross)) +
    theme_minimal() +
    theme(
        legend.position = "none",
        axis.text = element_blank(),
        axis.title = element_blank(),
        panel.grid = element_blank(),
        plot.margin = unit(rep(-1,4), "cm") 
    ) +
    coord_polar() + 
    geom_text(data=label_data, aes(x=id, y=gross+10, label=movie_title, hjust=hjust), color="black", fontface="bold",alpha=0.6, size=2.5, angle= label_data$angle, inherit.aes = FALSE) 

final_plot = 
  anno_plot+
    geom_segment(data=base_data, aes(x = start, y = -5, xend = end, yend = -5), colour = "black", alpha=0.8, size=0.6 , inherit.aes = FALSE)+
    geom_text(data=base_data, aes(x = title, y = -18, label=genres), colour = "black", alpha=0.6, size=3, fontface="bold", inherit.aes = FALSE)

final_plot
```

